import IcBack from './ic_back.svg'
import IcBackWhite from './ic_back_white.svg'
import IcButtonPlus from './ic_button_plus.svg'
import IcButtonMinus from './ic_button_minus.svg'
import IcChevronDown from './ic_chevron_down.svg'
import IcChevronRight from './ic_chevron_right.svg'
import IcHome from './ic_home.svg'
import IcHomeActive from './ic_home_active.svg'
import IcOrder from './ic_order.svg'
import IcOrderActive from './ic_order_active.svg'
import IcProfile from './ic_profile.svg'
import IcProfileActive from './ic_profile_active.svg'
import IcStar from './ic_star.svg'
import IcStarOff from './ic_star_off.svg'

export { IcBack, IcBackWhite, IcButtonPlus, IcButtonMinus, IcChevronDown, IcChevronRight, IcHome, IcHomeActive, IcOrder, IcOrderActive, IcProfile, IcProfileActive, IcStar, IcStarOff }